Repository MaloLM/pr74-scrum-app, pull requests merged in 2022-06, with the labels that each got.

#22 Feat/creating models
  Model/Backlog.cs
  Model/Comment.cs
  Model/Member.cs
  Model/ProductBacklog.cs
  Model/Project.cs
  Model/Sprint.cs
  Model/SprintBacklog.cs
  Model/User.cs
  Model/UserStory.cs
Labels: enhancement

#21 User register
  .gitignore
  App.config
  App.exemple.config
  Database.cs
  HomeForm.Designer.cs
  HomeForm.cs
  HomeForm.resx
  MainForm.Designer.cs
  MainForm.cs
  MainForm.resx
  Program.cs
  SignInForm.Designer.cs
  SignInForm.cs
  SignInForm.resx
  SignUpForm.Designer.cs
  SignUpForm.cs
  SignUpForm.resx
  UserController.cs
  database.sql
  packages.config
  pr74-scrum-app.csproj
Labels: enhancement

#34 feat: change the models
  Model/Comment.cs
  Model/Member.cs
  Model/ProductBacklog.cs
  Model/Project.cs
  Model/Sprint.cs
  Model/SprintBacklog.cs
  Model/User.cs
  Model/UserStory.cs
Labels: enhancement

#43 Feat/sprint view
  Controller/Controller.cs
  Controller/SidebarController.cs
  Controller/SprintController.cs
  Controller/UserController.cs
  Controller/UserStoryController.cs
  Model/Backlog.cs
  Model/Database.cs
  Model/Member.cs
  Model/ProductBacklog.cs
  Model/Sprint.cs
  Model/SprintBacklog.cs
  Model/User.cs
  Program.cs
  Ressources/high_priority.ico
  Ressources/low_priority.ico
  Ressources/medium_priority.ico
  View/Components/ListPanel.cs
  View/Components/NavBar.cs
  View/Components/SideBar.cs
  View/Components/UserStoryPanel.cs
  View/MainForm.Designer.cs
  View/MainForm.cs
  View/MainForm.resx
  View/SignInForm.cs
  View/SignUpForm.cs
  View/SprintForm.Designer.cs
  View/SprintForm.cs
  View/SprintForm.resx
  View/UserStoryForm.Designer.cs
  View/UserStoryForm.cs
  View/UserStoryForm.resx
  pr74-scrum-app.csproj
  pr74-scrum-app.csproj.user
Labels: feature

#52 Issue/26 project view
  .gitignore
  Controller/ProjectController.cs
  Controller/SprintController.cs
  Controller/UserController.cs
  Controller/UserStoryController.cs
  Model/Member.cs
  Model/ProductBacklog.cs
  Model/User.cs
  Ressources/imgProfil.ico
  View/Components/ListPanel.cs
  View/Components/NavBar.cs
  View/Components/SideBar.cs
  View/Components/UserStoryPanel.cs
  View/ProfilForm.Designer.cs
  View/ProfilForm.cs
  View/ProfilForm.resx
  View/Profildialog/CreateProjectForm.Designer.cs
  View/ProjectForm.Designer.cs
  View/ProjectForm.cs
  View/ProjectForm.resx
  View/ProjectViewSubForms/AddFeatureToBacklogForm.Designer.cs
  View/ProjectViewSubForms/AddFeatureToBacklogForm.cs
  View/ProjectViewSubForms/AddFeatureToBacklogForm.resx
  View/ProjectViewSubForms/AddNewMemberForm.Designer.cs
  View/ProjectViewSubForms/AddNewMemberForm.cs
  View/ProjectViewSubForms/AddNewMemberForm.resx
  View/ProjectViewSubForms/AddNewSprintForm.Designer.cs
  View/ProjectViewSubForms/AddNewSprintForm.cs
  View/ProjectViewSubForms/AddNewSprintForm.resx
  View/ProjectViewSubForms/ArchiveProjectConfirmationForm.Designer.cs
  View/ProjectViewSubForms/ArchiveProjectConfirmationForm.cs
  View/ProjectViewSubForms/ArchiveProjectConfirmationForm.resx
  View/ProjectViewSubForms/ConfirmationForm.Designer.cs
  View/ProjectViewSubForms/ConfirmationForm.cs
  View/ProjectViewSubForms/ConfirmationForm.resx
  View/ProjectViewSubForms/DisplayMemberInfo.Designer.cs
  View/ProjectViewSubForms/DisplayMemberInfo.cs
  View/ProjectViewSubForms/DisplayMemberInfo.resx
  View/ProjectViewSubForms/RemoveMemberFromProjectConfirmationPopUp.Designer.cs
  View/ProjectViewSubForms/RemoveMemberFromProjectConfirmationPopUp.cs
  View/ProjectViewSubForms/RemoveMemberFromProjectConfirmationPopUp.resx
  View/SprintForm.Designer.cs
  View/SprintForm.cs
  pr74-scrum-app.csproj
  pr74-scrum-app.csproj.user
Labels: bug, enhancement, feature

#54 fix: fixing the hidden forms problem + remove maximable forms
  View/Components/NavBar.cs
  View/HomeForm.Designer.cs
  View/HomeForm.cs
  View/ProfilForm.Designer.cs
  View/ProfilForm.cs
  View/ProjectForm.Designer.cs
  View/ProjectForm.cs
  View/SprintForm.Designer.cs
  View/SprintForm.cs
  View/UserStoryForm.Designer.cs
  View/UserStoryForm.cs
Labels: bug
